### ISSUE TITLE
File Not Found: __init__.py

### ISSUE THREAD

**Issue by camoody1** [dicksondickson/dickson-sci-fi-enhance-upscale#2]
Unable to import custom node at Comfy startup:

```
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1881, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'H:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ttplanet-controlnet\\__init__.py'

Cannot import H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ttplanet-controlnet module for custom nodes: [Errno 2] No such file or directory: 'H:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ttplanet-controlnet\\__init__.py'
```

I created the custom_nodes\ttplanet-controlnet folder and put both the TTP_tile_preprocessor_v5.py and config.json files into the folder.

What am I missing to make this work?

Thank you for your time.

**Comment by dicksondickson** [comment]
My bad. Rename "TTP_tile_preprocessor_v5.py" to "__init__.py" and it should work. Let me know!

**Comment by camoody1** [comment]
That's too funny. Yes sir. That resolved my issue. Now, I can test it out.

Thank you for your quick response!
